[[runners]]
  name = "${manager_name}"
  url = "${gitlab_url}"
  executor = "docker+machine"
  limit = ${limit}
  environment = ${environment}
  pre_build_script = "${pre_build_script}"
  post_build_script = "${post_build_script}"
  pre_clone_script = "${pre_clone_script}"
  request_concurrency = ${request_concurrency}
  output_limit = ${output_limit}
  [runners.docker]
    tls_verify = false
    image = "${image}"
    privileged = true
    disable_cache = false
    volumes = [%{ for volume in additional_volumes ~}"${volume}",%{ endfor ~}]
    shm_size = ${shm_size}
    pull_policy = "${pull_policy}"
%{ if s3_cache_enabled }
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
      BucketName = "${bucket_name}"
      BucketLocation = "${aws_region}"
      Insecure = false
%{ endif }
  [runners.machine]
    IdleCount = ${idle_count}
    IdleTime = ${idle_time}
    %{ if max_builds > 0 }MaxBuilds = ${max_builds}%{ endif }
    MachineDriver = "amazonec2"
    MachineName = "auto-scale-%s"
    MachineOptions = [
      "amazonec2-region=${aws_region}",
      "amazonec2-zone=${aws_az}",
      "amazonec2-vpc-id=${vpc_id}",
      "amazonec2-subnet-id=${subnet_id}",
      "amazonec2-security-group=${security_group}",
      "amazonec2-use-private-address=${use_private_address}",
      "amazonec2-iam-instance-profile=${instance_profile}",
      "amazonec2-instance-type=${instance_type}",
      "amazonec2-ami=${ami_id}",
      "amazonec2-root-size=${root_volume_size}",
      "amazonec2-use-ebs-optimized-instance=${ebs_optimized}",
      "amazonec2-monitoring=${enable_detailed_monitoring}",
      "amazonec2-request-spot-instance=${request_spot_instances}",
      "amazonec2-spot-price=${spot_price}",
      "amazonec2-block-duration-minutes=${spot_block_duration}",
      "amazonec2-tags=${tags}",
%{ if engine_registry_mirror_enabled }
      "engine-registry-mirror=http://ENGINE_REGISTRY_MIRROR_IP_ADDRESS:${engine_registry_mirror_port}",
%{ endif }
%{ for option in other_machine_options ~}
      "${option}",
%{ endfor ~}
    ]
%{ for autoscaling_period in autoscaling_periods ~}
    [[runners.machine.autoscaling]]
      Periods = [%{ for period in autoscaling_period.periods ~}"${period}",%{ endfor ~}]
      IdleCount = ${autoscaling_period.idle_count}
      IdleTime = ${autoscaling_period.idle_time}
      Timezone = "${autoscaling_period.timezone}"
%{ endfor ~}
